name: Afternoon Run (15:00-21:00 UTC)

on:
  schedule:
    # Her gün UTC 15:00'de çalıştır (TR saati ile 18:00)
    - cron: '0 15 * * *'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 358 # Yaklaşık 6 saat
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      INSTAGRAM_SESSIONID: ${{ secrets.INSTAGRAM_SESSIONID }} # Opsiyonel

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ffmpeg
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Telegram Bot
      run: python bot.py

    - name: Clean up temporary files (if any left)
      if: always()
      run: |
        echo "Cleaning up temporary files..."
        rm -rf temp_dl_* temp_cookie_*
        echo "Cleanup complete."
