name: Telegram Instagram Bot CI

on:
  schedule:
    - cron: '0 9 * * *' # Her gün UTC 09:00'da (TR saati ile 12:00) çalıştır
  workflow_dispatch: # Manuel tetikleme için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      INSTAGRAM_SESSIONID: ${{ secrets.INSTAGRAM_SESSIONID }} # Opsiyonel, kullanıcı ayarlayabilir

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Dockerfile'daki sürümle uyumlu veya projenin gerektirdiği sürüm

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Telegram Bot
      # timeout-minutes, tüm job adımlarının toplam süresidir.
      # Eğer botun kendisi düzgün kapanmazsa, bu timeout onu sonlandıracaktır.
      # Cron her gün UTC 12:00'de tetiklenecek ve bu adım yaklaşık 6 saat sonra (UTC 18:00 civarı) zaman aşımına uğrayacak.
      timeout-minutes: 358 # Yaklaşık 5 saat 58 dakika
      run: python bot.py

    - name: Clean up temporary files (if any left)
      # Botun içindeki finally bloğu temizlik yapmalı, bu ek bir önlem.
      if: always() # Her zaman çalışsın (başarılı veya başarısız olsa da)
      run: |
        echo "Temizlik yapılıyor (varsa kalan temp dosyaları)..."
        # rm -rf temp_* # Bot scripti kendi temp dosyalarını sildiği için bu genellikle gerekmeyebilir.
        # Ancak botun beklenmedik şekilde sonlanması durumunda kalıntıları temizlemek için eklenebilir.
        # Şimdilik botun kendi temizliğine güveniyoruz.
        echo "Temizlik tamamlandı."
